version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  elasticsearch:
    container_name: es-container
    image: elasticsearch:8.12.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  kibana:
      container_name: kb-container
      image: kibana:8.12.1
      environment:
        - ELASTICSEARCH_HOSTS=http://es-container:9200
      depends_on:
        - elasticsearch
      ports:
        - 5601:5601